const meta = {
  index: "はじめに",
  "getting-started": { title: "はじめ方" },
  agents: { title: "エージェント" },
  "tools-mcp": { title: "ツール & MCP", theme: { collapsed: true } },
  memory: { title: "メモリ", theme: { collapsed: true } },
  workflows: { title: "ワークフロー", theme: { collapsed: true } },
  "workflows-legacy": { title: "ワークフロー（レガシー）" },
  rag: { title: "RAG" },
  "local-dev": { title: "ローカル開発" },
  deployment: { title: "デプロイ" },
  "mastra-cloud": { title: "Mastra Cloud" },
  observability: { title: "オブザーバビリティ" },
  evals: { title: "評価" },
  frameworks: { title: "フレームワーク" },
  storage: { title: "ストレージ" },
  voice: { title: "音声" },
  community: "コミュニティ",
};
export default meta;
